# Generated by Django 4.2.8 on 2024-01-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankingApp', '0004_alter_netbankingcustomer_account_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='selectdistrict',
            new_name='district',
        ),
    ]
